// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://khalslwfyytimewzrkow.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtoYWxzbHdmeXl0aW1ld3pya293Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM4Nzc5NjksImV4cCI6MjA1OTQ1Mzk2OX0.nHE3bNvBLZ0yN_5JvPElBvUWKtp0oRuENeQas_mgtnI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);